branch-defaults:
  main:
    environment: MING-COMMERCE-UI-SERVICE
    group_suffix: null
global:
  application_name: MingCommerce-frontend
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
