name: ming-commerce-backend-master-deploy

on:
  push:
    branched:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      # Install Python 3.9
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Install the EB CLI using pip
      - name: Install EB CLI
        run: |
          python -m pip install --upgrade pip
          pip install awsebcli

      - name: Display EB CLI Version
        run: |
          eb --version
        shell: bash

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install NPM Packages
        run: |
          npm install

      - name: Build with Node
        run: |
          unset CI && npm run build

      - name: Release with Node
        run: |
          npm run deploy
